export const SET_IN_STOCK_ONLY = 'SET_IN_STOCK_ONLY';
export const SET_FILTERED_TEXT = 'SET_FILTERED_TEXT';
export const GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS';
export const SET_SORTBY_CODE = 'SET_SORTBY_CODE';
export const ADD_NEW_PRODUCT = 'ADD_NEW_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';

export const GET_ALL_CATEGORIES = 'GET_ALL_CATEGORIES';
export const ADD_NEW_CATEGORY = 'ADD_NEW_CATEGORY';

