export const SET_IN_STOCK_ONLY = 'SET_IN_STOCK_ONLY';
export const SET_FILTERED_TEXT = 'SET_FILTERED_TEXT';
export const GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS';
export const SET_SORTBY_CODE = 'SET_SORTBY_CODE';